using System.IO;
using FluentAssertions;
using Garupan.Content;
using Xunit;

namespace Garupan.Content.Tests.Maps;

public sealed class MapObstacleCsvTests
{
    private const string Header = "x,z,yaw,half_w_m,half_d_m,height_m";

    [Fact]
    public void Parses_rows_skipping_blank_and_comment_lines()
    {
        var csv = string.Join(
            '\n',
            "# generated by build-japanese-city.py",
            Header,
            "12.5,-3.0,1.57,10,8,24",
            string.Empty,
            "-40,80,0,6,6,12");

        var obstacles = MapObstacleCsv.Parse(csv);

        obstacles.Should().HaveCount(2);
        obstacles[0].Center.X.Should().Be(12.5f);
        obstacles[0].Center.Y.Should().Be(-3.0f);
        obstacles[0].YawRadians.Should().BeApproximately(1.57f, 1e-4f);
        obstacles[0].HalfWidthMeters.Should().Be(10f);
        obstacles[0].HalfDepthMeters.Should().Be(8f);
        obstacles[0].HeightMeters.Should().Be(24f);
    }

    [Fact]
    public void Rejects_a_header_mismatch()
    {
        var act = () => MapObstacleCsv.Parse("x,z,yaw\n0,0,0");

        act.Should().Throw<InvalidDataException>().WithMessage("*header mismatch*");
    }

    [Fact]
    public void Rejects_a_non_positive_extent()
    {
        var act = () => MapObstacleCsv.Parse($"{Header}\n0,0,0,0,8,24");

        act.Should().Throw<InvalidDataException>().WithMessage("*half_w_m*positive*");
    }

    [Fact]
    public void Rejects_a_non_finite_number()
    {
        var act = () => MapObstacleCsv.Parse($"{Header}\nInfinity,0,0,6,6,12");

        act.Should().Throw<InvalidDataException>().WithMessage("*x*finite*");
    }

    [Fact]
    public void Rejects_a_wrong_column_count()
    {
        var act = () => MapObstacleCsv.Parse($"{Header}\n0,0,0,6,6");

        act.Should().Throw<InvalidDataException>().WithMessage("*expected 6 columns*");
    }
}
